import { Invoice } from "@/components/invoice/Invoice";
import { InvoiceActions } from "@/components/invoice/InvoiceActions";
import { sampleInvoice } from "@/data/sampleInvoice";
import { FileText } from "lucide-react";

const Index = () => {
  return (
    <div className="min-h-screen bg-background py-8 px-4 lg:py-12">
      <div className="max-w-5xl mx-auto">
        {/* Page Header */}
        <div className="no-print mb-8 text-center lg:text-left">
          <div className="flex items-center justify-center lg:justify-start gap-3 mb-4">
            <div className="w-12 h-12 rounded-xl gradient-navy flex items-center justify-center">
              <FileText className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-3xl font-serif font-bold text-foreground">
                Proforma Invoice
              </h1>
              <p className="text-sm text-muted-foreground">
                Premium Invoice Management System
              </p>
            </div>
          </div>
        </div>

        {/* Actions */}
        <InvoiceActions />

        {/* Invoice */}
        <Invoice data={sampleInvoice} />

        {/* Footer */}
        <div className="no-print mt-8 text-center text-sm text-muted-foreground">
          <p>Generated by Premium Invoice System • Secure & Reliable</p>
        </div>
      </div>
    </div>
  );
};

export default Index;
